-- Add directions_url to external_accommodations
ALTER TABLE external_accommodations ADD COLUMN IF NOT EXISTS directions_url TEXT;

-- Seed all hotels (run once — safe to re-run, upserts on name)
INSERT INTO external_accommodations (name, description, url, directions_url, sort_order, is_active)
VALUES
  ('Hotel Bremon',             'Small hotel in the medieval town of Cardona.',                                        'https://hotelbremon.com/',                                                                                                                                           'https://www.google.com/maps/search/?api=1&query=Carrer%20Cambres%2C%2015%2C%2008261%20Cardona%2C%20Barcelona',          1, true),
  ('Parador de Cardona',       'Stunning castle hotel overlooking Cardona.',                                          'https://parador.es/es/paradores/parador-de-cardona',                                                                                                                  'https://www.google.com/maps/search/?api=1&query=Castell%20de%20Cardona%2C%20s%2Fn%2C%2008261%20Cardona%2C%20Barcelona', 2, true),
  ('AT Cardona',               'Tourist apartments in the village of Cardona.',                                       'https://atcardona.com/',                                                                                                                                              'https://www.google.com/maps/search/?api=1&query=Ctra.%20del%20Miracle%2C%2021%2C%2008261%20Cardona%2C%20Barcelona',     3, true),
  ('Ramon Park Hotel',         'Hotel in a natural park setting near Santpedor.',                                     'https://ramonparkhotel.com/',                                                                                                                                         'https://www.google.com/maps/search/?api=1&query=Cam%C3%AD%20de%20Juncadella%20s%2Fn%2C%2008251%20Santpedor%2C%20Barcelona', 4, true),
  ('Dom Bosco',                'Rustic masia with modern amenities in Castellnou de Bages.',                          'https://dombosco.odoo.com/',                                                                                                                                          'https://www.google.com/maps/search/?api=1&query=Pla%C3%A7a%20l%27Esgl%C3%A9sia%2C%20s%2Fn%2C%2008251%20Castellnou%20de%20Bages%2C%20Barcelona', 5, true),
  ('Hostal Somnis',            'Cozy hostel nearby.',                                                                 'https://hostalsomnis.com/',                                                                                                                                           'https://www.google.com/maps/search/?api=1&query=C%2F%20Diputaci%C3%B3%2C%20n%C2%BA8%2C%20S%C3%BAria%2C%20Barcelona',   6, true),
  ('Restaurant Hostel Ca Fuster', 'Charming mini castle experience.',                                                 'https://www.barcelonaesmoltmes.cat/es/detalle-del-viaje/-/dades/3bd3LPr67IZT/detall/17_14001_497637/restaurant-hostal-cal-fuster', NULL,                                                                                                                                              7, true),
  ('Casa Albareda',            'Rural estate with pool, tennis court and full amenities.',                            'https://www.casaalbareda.com/index.php',                                                                                                                              'https://www.google.com/maps/search/?api=1&query=08673%20Viver%20i%20Serrateix%2C%20Barcelona',                           8, true),
  ('Camping Hostalet',         'Glamping bungalows — great if you fancy something different.',                        'https://campinghostalet.cat/',                                                                                                                                        'https://www.google.com/maps/search/?api=1&query=Casa%20Rastrillo%2C%20s%2Fn%2C%2008673%20Serrateix%2C%20Barcelona',     9, true),
  ('La Prensa Hotel Rural',    'Historic rural hotel and restaurant in Cardona.',                                     'https://www.lapremsamoli.cat/',                                                                                                                                       'https://www.google.com/maps/search/?api=1&query=Carrer%20de%20l%27Esgl%C3%A9sia%2C%2053%2C%2008261%20Cardona%2C%20Barcelona', 10, true)
ON CONFLICT (name) DO UPDATE SET
  description    = EXCLUDED.description,
  url            = EXCLUDED.url,
  directions_url = EXCLUDED.directions_url,
  sort_order     = EXCLUDED.sort_order,
  is_active      = EXCLUDED.is_active;
