ALTER TABLE guests ADD COLUMN IF NOT EXISTS transport_needed BOOLEAN DEFAULT NULL;
ALTER TABLE guests ADD COLUMN IF NOT EXISTS transport_from TEXT DEFAULT NULL;
ALTER TABLE guests ADD COLUMN IF NOT EXISTS transport_return BOOLEAN DEFAULT NULL;
